`IiwaDriver`: Create controller MBP from scenario file
RussTedrake/manipulation pull request #317
Opened 2024-06-06 23:03 UTC by siddancha

Fixed #316 

- Create the controller plant for the `IiwaDriver` by reusing the user-provided scenario, instead of creating a custom iiwa (hardcoded to iiwa7) and the WSG schunk.
- This is enabled by being able to freeze child instances i.e. removing non-weld joints in the child instance and replacing them with weld joints. This is in-turn made possible by this recently landed PR: (https://github.com/RobotLocomotion/drake/pull/21397)

2024-06-06 23:11 UTC, siddancha commented
There is currently an issue with `plant.GetJointActuatorIndices(child_instance)` that returns an empty list, even though `plant.GetJointActuatorByName('left_finger_sliding_joint', child_instance)` returns a joint actuator.

Seems like a potential bug in Drake, and is what is causing the tests to fail. Will dig into this and potentially raise an issue on the drake's Github.

2024-06-07 04:30 UTC, siddancha commented
Added `GetJointActuatorIndices` bug report and a simple reproduction here: https://github.com/RobotLocomotion/drake/issues/21547

2024-06-07 05:05 UTC, siddancha commented
Realized from bug report (https://github.com/RobotLocomotion/drake/issues/21547) that `GetJointActuatorIndices(model_instance)` cannot be used pre-finalize. Using @jwnimmer-tri 's solution to call `plant.GetJointActuatorIndices()` and remove the ones corresponding to the joints to be removed.

2024-06-07 10:06 UTC, RussTedrake commented
thanks!  ironically, i already did all this in https://github.com/RussTedrake/manipulation/blob/master/book/mobile/exercises/mobile_base_ik.ipynb 
will review this morning.

2024-06-07 10:12 UTC, RussTedrake requested changes
one small request.  otherwise LGTM.  Thanks!

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/317#-:-NzmApUX06g01ZhTX7rN:bryjds1)* status: all files reviewed, 1 unresolved discussion (waiting on @siddancha)

___
*[`manipulation/station.py` line 395 at r3](https://reviewable.io/reviews/RussTedrake/manipulation/317#-NzmA7bP36UDYIc4bHWK:-NzmA7bQ62ZkmpMf6kDh:bgifoce) ([raw file](https://github.com/RussTedrake/manipulation/blob/1c6b07a8385841d32f1ec1cc9738370ea71dd497/manipulation/station.py#L395)):*
> ```Python
>         frame_on_child = joint.frame_on_child()
>         plant.RemoveJoint(joint)
>         plant.WeldFrames(frame_on_parent, frame_on_child)
> ```

per my mobile_ik example, I preferred the extra line using the WeldJoint constructor so that I could keep the joint name the same.

Also, if there are mimic joints anywhere in the model, this will throw.  But I think that's ok for now.


<!-- Sent from Reviewable.io -->

2024-06-07 11:07 UTC, siddancha commented
> thanks! ironically, i already did all this in https://github.com/RussTedrake/manipulation/blob/master/book/mobile/exercises/mobile_base_ik.ipynb

:upside_down_face:

> per my mobile_ik example, I preferred the extra line using the WeldJoint constructor so that I could keep the joint name the same.

Makes sense! I just switched to the `WeldJoint` constructor.

2024-06-07 11:13 UTC, siddancha reviewed
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/317)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @RussTedrake)

___
*[`manipulation/station.py` line 395 at r3](https://reviewable.io/reviews/RussTedrake/manipulation/317#-NzmA7bP36UDYIc4bHWK:-NzmNxUsAMIEyDV0CfIN:b-pywpg1) ([raw file](https://github.com/RussTedrake/manipulation/blob/1c6b07a8385841d32f1ec1cc9738370ea71dd497/manipulation/station.py#L395)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

per my mobile_ik example, I preferred the extra line using the WeldJoint constructor so that I could keep the joint name the same.

Also, if there are mimic joints anywhere in the model, this will throw.  But I think that's ok for now.
</blockquote></details>

Makes sense! I just switched to the `WeldJoint` constructor.


<!-- Sent from Reviewable.io -->

2024-06-07 11:34 UTC, merged

2024-06-07 11:35 UTC, siddancha reviewed
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/317)* status: all files reviewed, 1 unresolved discussion

___
*[`pyproject.toml` line 5 at r4](https://reviewable.io/reviews/RussTedrake/manipulation/317#-NzmPmet2mDSdttzZRhG:-NzmQsBI7f5KFAofN4kx:be35jad) ([raw file](https://github.com/RussTedrake/manipulation/blob/b3e3a67100e5a023bfe39eddddd3a1530badeef1/pyproject.toml#L5)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- i presume that this means you would like me to roll some pip wheels once this lands?
</blockquote></details>

If it's not a hassle/concern? Otherwise I can just also do `pip install git+https://github.com/RussTedrake/manipulation@master` and not rely on PyPI releases.


<!-- Sent from Reviewable.io -->

2024-06-07 11:43 UTC, RussTedrake commented
*[`pyproject.toml` line 5 at r4](https://reviewable.io/reviews/RussTedrake/manipulation/317#-NzmPmet2mDSdttzZRhG:-NzmVi_N0xdBMnX1sO3B:bdbya6v) ([raw file](https://github.com/RussTedrake/manipulation/blob/b3e3a67100e5a023bfe39eddddd3a1530badeef1/pyproject.toml#L5)):*
<details><summary><i>Previously, siddancha (Siddharth Ancha) wrote…</i></summary><blockquote>

If it's not a hassle/concern? Otherwise I can just also do `pip install git+https://github.com/RussTedrake/manipulation@master` and not rely on PyPI releases.
</blockquote></details>

Done.  (i've pushed to pypi)


<!-- Sent from Reviewable.io -->

2024-06-07 11:47 UTC, siddancha reviewed
> *[Reviewable](https://reviewable.io/reviews/RussTedrake/manipulation/317)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`pyproject.toml` line 5 at r4](https://reviewable.io/reviews/RussTedrake/manipulation/317#-NzmPmet2mDSdttzZRhG:-NzmWcw5Evfb4VWCNb2z:b-9755fn) ([raw file](https://github.com/RussTedrake/manipulation/blob/b3e3a67100e5a023bfe39eddddd3a1530badeef1/pyproject.toml#L5)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

Done.  (i've pushed to pypi)
</blockquote></details>

Thank you!


<!-- Sent from Reviewable.io -->